<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.dows.framework</groupId>
        <artifactId>rade-framework</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>rade-oss</artifactId>
    <packaging>pom</packaging>


    <modules>
        <module>oss-boot</module>
        <module>oss-api</module>
        <module>oss-rest</module>
        <module>oss-channel</module>
    </modules>

    <dependencies>
        <!--<dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-s3</artifactId>
            <version>1.12.177</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>-->
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <!--<dependency>
                <groupId>org.dows.framework</groupId>
                <artifactId>oss-engine</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.framework</groupId>
                <artifactId>oss-wrapper</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.framework</groupId>
                <artifactId>oss-local</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.dows.framework</groupId>
                <artifactId>oss-ftp</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.dows.framework</groupId>
                <artifactId>oss-sftp</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.dows.framework</groupId>
                <artifactId>oss-minio</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.dows.framework</groupId>
                <artifactId>oss-tencent</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.dows.framework</groupId>
                <artifactId>oss-qiniu</artifactId>
                <version>${project.version}</version>
            </dependency>-->
        </dependencies>
    </dependencyManagement>

</project>
