<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>org.dows.framework</groupId>
        <artifactId>rade-oss</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>oss-channel</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>oss-local</module>
        <module>oss-ftp</module>
        <module>oss-sftp</module>
        <module>oss-tencent</module>
        <module>oss-minio</module>
        <module>oss-qiniu</module>
        <module>oss-aliyun</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>org.dows.framework</groupId>
            <artifactId>oss-api</artifactId>
        </dependency>
    </dependencies>
</project>
